export {createProduct} from "./productCreate.controller.js"
export {deleteProduct} from "./productDelete.controller.js"
export {getCategoryProducts} from "./productsGetWithCategory.controller.js"
export {updateProduct} from "./productUpdate.controller.js"
export {getAllProducts} from "./productsGetAll.controller.js"
export {barcodeAddToProduct} from "./productBarcode.controller.js"